custom_cursor_colors = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x969896"
blue = "0x5F676A"
cyan = "0xa3685a"
green = "0x39CCA4"
magenta = "0xe0e0e0"
red = "0xde935f"
white = "0xffffff"
yellow = "0xb294bb"

[colors.cursor]
cursor = "0x39CCA4"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0x39CCA4"
magenta = "0xb294bb"
red = "0xE83838"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[cursor]
style = "Beam"

[font]
size = 9.0

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
